<?php
declare(strict_types=1);
$root=dirname(__DIR__,2); require $root.'/zef_framework_v2.5.0-beta1.php';
use Zef\Framework\Observability\BatchSpanProcessor; use Zef\Framework\Observability\InMemorySpanExporter; use Zef\Framework\Observability\Telemetry; use Zef\Framework\Observability\Tracer; use Zef\Framework\Observability\CounterMeter; use Zef\Framework\Observability\SpanContext; use Zef\Framework\Observability\SpanData;
function g42a(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);} function g42e(string $k,?string $v):void{putenv($v===null?$k:$k.'='.$v);} 
$keys=['ZEF_OTEL_EXPORTER_OTLP_ENDPOINT','ZEF_OTEL_EXPORT_TIMEOUT_MS','ZEF_OTEL_MAX_QUEUE','ZEF_OTEL_BATCH_SIZE','ZEF_OTEL_RETRY_ATTEMPTS','ZEF_OTEL_RETRY_DELAY_MS','ZEF_OTEL_RETRY_DELAY_CAP_MS','ZEF_OTEL_SHUTDOWN_DRAIN_MS']; foreach($keys as $k)g42e($k,null); $results=[];
try{
 g42e('ZEF_OTEL_ENABLED','1');g42e('ZEF_OTEL_EXPORTER_OTLP_ENDPOINT','http://collector.example.test');g42a(Telemetry::fromEnvironment()->isEnabled(),'enabled config failed');$results[]='config-enabled';
 g42e('ZEF_OTEL_EXPORTER_OTLP_ENDPOINT','https://user:pass@example.test');$th=false;try{Telemetry::fromEnvironment();}catch(InvalidArgumentException){$th=true;}g42a($th,'embedded endpoint credentials accepted');$results[]='endpoint-secret-rejection';
 g42e('ZEF_OTEL_EXPORTER_OTLP_ENDPOINT','http://collector.example.test');g42e('ZEF_OTEL_EXPORT_TIMEOUT_MS','bad');$th=false;try{Telemetry::fromEnvironment();}catch(InvalidArgumentException){$th=true;}g42a($th,'invalid timeout accepted');$results[]='config-validation';g42e('ZEF_OTEL_EXPORT_TIMEOUT_MS',null);
 $count=0;$exp=new class($count) implements \Zef\Framework\Observability\SpanExporterInterface{public function __construct(private int &$c){}#[\Override]public function export(array $s):void{++$this->c;if($this->c<3)throw new RuntimeException('transient');}#[\Override]public function shutdown():void{}};g42e('ZEF_OTEL_RETRY_ATTEMPTS','2');g42e('ZEF_OTEL_RETRY_DELAY_MS','0');g42e('ZEF_OTEL_RETRY_DELAY_CAP_MS','0');$p=new BatchSpanProcessor($exp,8,8);$ctx=new SpanContext(str_repeat('a',32),str_repeat('b',16),true);$s=new SpanData('retry',$ctx,null,1,2,1,2,'OK',null,[],[]);$p->onEnd($s);$p->flush();g42a($count===3,'retry count mismatch');$results[]='bounded-retry';
 $count=0;$exp=new class($count) implements \Zef\Framework\Observability\SpanExporterInterface{public function __construct(private int &$c){}#[\Override]public function export(array $s):void{++$this->c;throw new InvalidArgumentException('permanent');}#[\Override]public function shutdown():void{}};$p=new BatchSpanProcessor($exp,8,8);$p->onEnd($s);$p->flush();g42a($count===1,'permanent failure retried');$results[]='permanent-no-retry';
 $mem=new InMemorySpanExporter();$p=new BatchSpanProcessor($mem,2,2);$t=new Telemetry(new Tracer($p),new CounterMeter(),$p,null,null,true);$t->startSpan('one')->end();$t->recordLog('INFO','safe',['safe'=>'ok']);$t->flush();$t->shutdown();$t->shutdown();g42a(count($mem->spans())===1,'flush failed');$results[]='flush-shutdown-idempotence';
 g42e('ZEF_OTEL_ENABLED','0');g42e('ZEF_OTEL_EXPORTER_OTLP_ENDPOINT',null);echo 'G4.2 boundary: '.count($results).'/'.count($results).' PASS'.PHP_EOL;foreach($results as $r)echo 'PASS '.$r.PHP_EOL;
}catch(Throwable $e){fwrite(STDERR,'FAIL: '.$e->getMessage().PHP_EOL);exit(1);}
