<?php
declare(strict_types=1);
$root=dirname(__DIR__);
$files=[
'composer.json','composer.lock','phpstan.neon.dist','phpstan-baseline.neon','phpstan-baseline-snapshot.json','quality-gate.php','build/build-monolith.php',
'zef_framework_v2.5.0-beta1.php','dist/zef_framework_v2.5.0-beta1-phase5.php',
'ROADMAP.md','PROJECT_HANDOVER.md','RELEASE_GOVERNANCE_HARDENING_AUDIT.md',
'docs/architecture/ADR-014-supply-chain-security.md','docs/architecture/ADR-015-continuous-quality-governance.md','docs/architecture/ADR-016-canonical-project-path-topology.md','docs/architecture/ADR-017-release-governance-hardening.md','docs/architecture/ADR-018-roadrunner-production-hardening.md','docs/architecture/ADR-021-roadrunner-worker-failure-recovery.md','docs/architecture/ADR-022-g4-observability-operational-boundary.md','docs/architecture/ADR-025-G4_4-configuration-secrets-governance.md','docs/architecture/ADR-026-G4_5-resource-protection-backpressure.md','docs/architecture/ADR-027-G4_6-distributed-messaging-foundation.md','docs/architecture/ADR-028-G4_7-enterprise-quality-hardening.md','docs/G4_1_IMPLEMENTATION.md','docs/G4_1_SOURCE_DRIFT.md','docs/G4_1_DECISION_RECORD.json',
'tools/verify-baseline-drift.php','tools/documentation-consistency.php','tools/verify-release-integrity.php','tools/verify-project-paths.php','tools/release-governance.php','tools/generate-provenance.php','tools/rr-healthcheck.php','worker.php','.rr.yaml','.rr.g3.yaml','tests/Regression/RoadRunnerRuntimeG2Test.php','tests/Regression/RoadRunnerRuntimeG3Test.php','benchmarks/g3_worker_failure_recovery.sh','benchmarks/g3_worker_hardening.sh','tests/Architecture/G3RuntimeGovernanceTest.php','tests/Architecture/PublicSurfaceG3GovernanceTest.php','tests/Regression/G4_1_ObservabilityOperationalResilienceTest.php','tests/Regression/G4_2_TelemetryIntegrationBoundaryTest.php','tests/Integration/G4_2_OTLPBoundaryIntegrationTest.php','tests/Regression/G4_3_RuntimeFoundationTest.php','docs/ROADRUNNER_G3.md','docs/architecture/ADR-020-roadrunner-health-recovery-g3.md','docs/PRODUCTION_WEB_RESILIENCE_QUALIFICATION.md','benchmarks/g3_production_web_resilience.sh','benchmarks/g3_long_running_soak.sh','benchmarks/g3_request_state_isolation.php','docs/SOAK_CAPACITY_EVIDENCE.md','docs/SOAK_CAPACITY_QUALIFICATION_README.md','benchmarks/g3_capacity_characterization.sh','benchmarks/g3_soak_60s.sh','benchmarks/g3_long_duration_soak.sh','docs/LONG_DURATION_SOAK_QUALIFICATION.md',
'docs/LONG_DURATION_SOAK_REMEDIATION.md','src/Framework/Resource/Resource.php','tests/Unit/G4_4ToG4_6FoundationTest.php','tests/Architecture/PublicSurfaceG4_7GovernanceTest.php','tests/Architecture/public-surface-baseline-beta1-g4_3.json','tests/Architecture/public-surface-baseline-beta1-g4_7.json','tests/Architecture/public-surface-delta-v2.5.0-beta1-g4.7.json','tools/enterprise-preflight.php','tools/generate-full-sha256.php','tools/verify-full-sha256.php',
'supply-chain/bom.cdx.json','supply-chain/provenance.intoto.json',
'src/Framework/Observability/Correlation.php','tests/Unit/G4_8CorrelationContextTest.php','tests/Architecture/G4_8W4CorrelationGovernanceTest.php','tests/Architecture/G4_8W4PublicSurfaceGovernanceTest.php','tests/Architecture/public-surface-delta-v2.5.0-beta1-g4.8-w4.json','tools/g4_8_w4_contract_smoke.php','tools/g4_8_w4_failure_matrix.php','tools/g4_8_w4_performance.php','src/Framework/Security/Distributed.php','tests/Unit/G4_8DistributedSecurityTest.php','tests/Architecture/G4_8W5SecurityGovernanceTest.php','tests/Architecture/G4_8W5PublicSurfaceGovernanceTest.php','tests/Architecture/public-surface-delta-v2.5.0-beta1-g4.8-w5.json','tools/g4_8_w5_contract_smoke.php','tools/g4_8_w5_failure_matrix.php','tools/g4_8_w5_performance.php','src/Framework/Qualification/Governance.php','tests/Unit/G4_8QualificationGovernanceTest.php','tests/Architecture/G4_8W6QualificationGovernanceTest.php','tests/Architecture/G4_8W6PublicSurfaceGovernanceTest.php','tests/Architecture/public-surface-delta-v2.5.0-beta1-g4.8-w6.json','tests/Architecture/run-all.php','tools/g4_8_w6_contract_smoke.php','docs/architecture/ADR-034-QUALIFICATION-GOVERNANCE.md',
];
$out=[];
foreach($files as $f){$p=$root.'/'.$f;if(!is_file($p))throw new RuntimeException('Missing release artifact: '.$f);$h=hash_file('sha256',$p);if($h===false)throw new RuntimeException('Cannot hash: '.$f);$out[]=$h.'  '.$f;}
file_put_contents($root.'/supply-chain/SHA256SUMS-i.txt',implode("\n",$out)."\n");
echo "Release manifest generated: ".count($out)." entries\n";
