<?php
declare(strict_types=1);
$root=dirname(__DIR__); $fail=[];
/** @return array<string,mixed> */
function readJsonStrict(string $path): array { $decoded=json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR); if(!is_array($decoded)) throw new RuntimeException('Expected object: '.$path); /** @var array<string,mixed> $typed */ $typed=$decoded; return $typed; }
/** @param array<mixed,mixed> $record */
function stringFieldStrict(array $record,string $key,string $fallback=''): string { $value=$record[$key]??$fallback; return is_string($value)?$value:$fallback; }
$lock=readJsonStrict($root.'/composer.lock'); $prod=[]; $packages=$lock['packages']??[]; $dev=$lock['packages-dev']??[]; if(!is_array($packages)||!is_array($dev)) throw new RuntimeException('Invalid composer lock package sections.'); foreach($packages as $p){if(!is_array($p))throw new RuntimeException('Invalid package record.'); /** @var array<string,mixed> $p */$prod[]=stringFieldStrict($p,'name');} foreach($dev as $p){if(!is_array($p))throw new RuntimeException('Invalid dev package record.'); /** @var array<string,mixed> $p */$n=stringFieldStrict($p,'name');if(in_array($n,$prod,true))$fail[]='Duplicate package across lock sections: '.$n;}
if(stringFieldStrict($lock,'content-hash')==='')$fail[]='composer.lock missing content-hash.';
$sbom=readJsonStrict($root.'/supply-chain/bom.cdx.json'); if(($sbom['bomFormat']??null)!=='CycloneDX'||($sbom['specVersion']??null)!=='1.7')$fail[]='SBOM must be CycloneDX 1.7.';
$components=$sbom['components']??[];if(!is_array($components))$fail[]='SBOM components invalid.';$seen=[];if(is_array($components))foreach($components as $c){if(!is_array($c)){$fail[]='Invalid SBOM component.';continue;} /** @var array<string,mixed> $c */$r=stringFieldStrict($c,'bom-ref');if($r===''||isset($seen[$r]))$fail[]='Invalid/duplicate SBOM bom-ref: '.$r;$seen[$r]=true;}$expected=count($packages)+count($dev);if(count($seen)!==$expected)$fail[]='SBOM component count mismatch.';
$prov=readJsonStrict($root.'/supply-chain/provenance.intoto.json');if(($prov['predicateType']??null)!=='https://slsa.dev/provenance/v1')$fail[]='Provenance predicateType must be SLSA v1.';$subjects=$prov['subject']??[];if(!is_array($subjects)||$subjects===[])$fail[]='Provenance has no subjects.';if(is_array($subjects))foreach($subjects as $subject){if(!is_array($subject)){$fail[]='Invalid provenance subject.';continue;} /** @var array<string,mixed> $subject */$name=stringFieldStrict($subject,'name');$digest=$subject['digest']??[];$expectedHash=is_array($digest)?stringFieldStrict($digest,'sha256'):'';$path=$root.'/'.$name;if(!is_file($path)){$fail[]='Provenance subject missing: '.$name;continue;}$actual=hash_file('sha256',$path);if($actual===false||$expectedHash===''||!hash_equals($expectedHash,$actual))$fail[]='Provenance subject hash mismatch: '.$name;}
if($fail){foreach($fail as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo"Supply-chain verification: PASS\n";
